Todo app
edemagbenyo/todoapp pull request #1
Opened 2020-03-27 22:15 UTC by edemagbenyo

2020-03-28 01:34 UTC, Torres-ssf requested changes
### Changes Required :warning: 
Hi there team :hand: 
I must say, you did an awesome work in this project. It sure looks fine :clap: :+1: 

However, we have some changes to make before moving on.

- [x] I notice you forgot to summarize the changes made in the PR description. This is a good practice that will make your PR look more professional. Please take a look [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) to see how you can make your repo looks more professional.
![Screenshot from 2020-03-27 22-07-39](https://user-images.githubusercontent.com/30977845/77811158-68ce6f80-7077-11ea-9224-ccac508499a5.png)

- [ ] Good job on your README file, it's looking really nice. But I notice you forgot to add instructions on how to use your app and the scripts it uses. You can benefit from that since it's a good practice and will make your repo look more professional.

- [ ] The main.js file inside the dist directory works fine, all functionalities are working nice and the save to local storage as well. But when I run `npm run build` or `npm run watch`, the new generated main.js seems to stop working properly. Maybe this is happening only on my end. Can you confirm that?
![problem](https://user-images.githubusercontent.com/30977845/77811497-75ec5e00-7079-11ea-9658-3f9c37b0ed20.gif)

Please kindly submit for code review again after making these changes.
Feel free to message me on slack if you have any question

Happy coding :computer: 
**Sergio Torres**

2020-03-28 01:34 UTC, Torres-ssf commented on dist/index.html
> +        <button class="btn btn-danger mt-3" id="btnProject">Add Project</button>
Please let me ask, why do you have two `Add Projects` buttons and also 2 `Add tasks` buttons in your HTML file? :thinking:

2020-03-28 01:34 UTC, Torres-ssf commented on package.json
> +    "watch": "webpack --watch --mode development",
Maybe it makes more sense to change this script name to dev since its purpose it's for development.

2020-03-28 01:34 UTC, Torres-ssf commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Since no tests were implemented we can safely delete the test script :smiley:

2020-03-30 22:16 UTC, maelfosso requested changes
# Changes required :red_circle:

Hello,
Thank you for the improvements you've done !
However, there are some bugs that should be fixed.

1. The TODO creation form doesn't have any field for the Project is assigned to

2. There is an error when trying to **edit** a created TODO
![Screenshot from 2020-03-30 18-06-12](https://user-images.githubusercontent.com/8848104/77966529-3d36c980-72b1-11ea-9665-f110d1f566a3.png)

3. There is also that error met when using the checkbox above the TODO
![Screenshot from 2020-03-30 18-08-10](https://user-images.githubusercontent.com/8848104/77966673-7cfdb100-72b1-11ea-8359-8083e2b318e5.png)

4. After submiting the Project creation form, the project's name is still into the field

5. You can't handle TODO and Project into the same file. Please, re-read this [article](http://aspiringcraftsman.com/2011/12/08/solid-javascript-single-responsibility-principle/) about SOLID

6. Also, The user should be able to filter the TODO by project.

Kindly make the suggested changes and submit a new code review request,
Thanks

Mael FOSSO

2020-03-31 23:11 UTC, maelfosso approved these changes
# Congratulations :clap:

You can merge it :+1:
Good luck with the next step :handshake:

Mael FOSSO

2020-03-31 23:56 UTC, merged